import unittest
from cls_file_format import *

class Test_FileFormat(unittest.TestCase):
    def test_init(self):
        # no headers
        result = FileFormat("abc\ndef")
        self.assertEqual(len(result.file_root.children), 0)
        self.assertEqual(len(result.parsing_errors), 0)
        # one header
        result = FileFormat("abc\ndef\n# A\nghi")
        self.assertEqual(len(result.file_root.children), 1)
        self.assertEqual(result.file_root.children[0].lines, ['ghi'])
        self.assertEqual(result.file_root.children[0].get_id(), 'A')
        self.assertEqual(len(result.parsing_errors), 0)
        # one set of nested headers
        result = FileFormat("# A\nabc\n## A.A\ndef\n### A.A.A\nghi")
        self.assertEqual(len(result.file_root.children), 1)
        self.assertEqual(result.file_root.children[0].lines, ['abc'])
        self.assertEqual(result.file_root.children[0].get_id(), 'A')
        self.assertEqual(len(result.file_root.children[0].children), 1)
        self.assertEqual(result.file_root.children[0].children[0].lines, ['def'])
        self.assertEqual(result.file_root.children[0].children[0].get_id(), 'A.A')
        self.assertEqual(len(result.file_root.children[0].children[0].children), 1)
        self.assertEqual(result.file_root.children[0].children[0].children[0].lines, ['ghi'])
        self.assertEqual(result.file_root.children[0].children[0].children[0].get_id(), 'A.A.A')
        self.assertEqual(len(result.file_root.children[0].children[0].children[0].children), 0)
        self.assertEqual(len(result.parsing_errors), 0)
        # multiple sets of nested headers
        result = FileFormat("# A\nabc\n## A.A\ndef\n# B\nghi\n## B.A\njkl")
        self.assertEqual(len(result.file_root.children), 2)
        self.assertEqual(result.file_root.children[0].lines, ['abc'])
        self.assertEqual(result.file_root.children[0].get_id(), 'A')
        self.assertEqual(len(result.file_root.children[0].children), 1)
        self.assertEqual(result.file_root.children[0].children[0].lines, ['def'])
        self.assertEqual(result.file_root.children[0].children[0].get_id(), 'A.A')
        self.assertEqual(len(result.file_root.children[0].children[0].children), 0)
        self.assertEqual(result.file_root.children[1].lines, ['ghi'])
        self.assertEqual(result.file_root.children[1].get_id(), 'B')
        self.assertEqual(len(result.file_root.children[1].children), 1)
        self.assertEqual(result.file_root.children[1].children[0].lines, ['jkl'])
        self.assertEqual(result.file_root.children[1].children[0].get_id(), 'B.A')
        self.assertEqual(len(result.file_root.children[1].children[0].children), 0)
        self.assertEqual(len(result.parsing_errors), 0)
        # jump back multiple levels AND add multiple children
        result = FileFormat("# A\nabc\n## A.A\ndef\n### A.A.A\nghi\n#### A.A.A.A\njkl\n## A.B\nmno")
        self.assertEqual(len(result.file_root.children), 1)
        self.assertEqual(result.file_root.children[0].lines, ['abc'])
        self.assertEqual(result.file_root.children[0].get_id(), 'A')
        self.assertEqual(len(result.file_root.children[0].children), 2)
        self.assertEqual(result.file_root.children[0].children[0].lines, ['def'])
        self.assertEqual(result.file_root.children[0].children[0].get_id(), 'A.A')
        self.assertEqual(len(result.file_root.children[0].children[0].children), 1)
        self.assertEqual(result.file_root.children[0].children[0].children[0].lines, ['ghi'])
        self.assertEqual(result.file_root.children[0].children[0].children[0].get_id(), 'A.A.A')
        self.assertEqual(len(result.file_root.children[0].children[0].children), 1)
        self.assertEqual(result.file_root.children[0].children[0].children[0].children[0].lines, ['jkl'])
        self.assertEqual(result.file_root.children[0].children[0].children[0].children[0].get_id(), 'A.A.A.A')
        self.assertEqual(len(result.file_root.children[0].children[0].children[0].children[0].children), 0)
        self.assertEqual(result.file_root.children[0].children[1].lines, ['mno'])
        self.assertEqual(result.file_root.children[0].children[1].get_id(), 'A.B')
        self.assertEqual(len(result.file_root.children[0].children[1].children), 0)
        self.assertEqual(len(result.parsing_errors), 0)
        # warns about skipped levels
        result = FileFormat("# A\nabc\n### A.A.A\ndef")
        self.assertEqual(len(result.file_root.children), 1)
        self.assertEqual(result.file_root.children[0].lines, ['abc'])
        self.assertEqual(result.file_root.children[0].get_id(), 'A')
        self.assertEqual(len(result.file_root.children[0].children), 1)
        self.assertEqual(result.file_root.children[0].children[0].lines, ['def'])
        self.assertEqual(result.file_root.children[0].children[0].get_id(), 'A.A')
        self.assertEqual(len(result.file_root.children[0].children[0].children), 0)
        self.assertEqual(len(result.parsing_errors), 1)
        # ignore everything after duplicate section
        result = FileFormat("# A\nabc\n# Duplicate: All Final Sections\ndef\n## A.A\nghi")
        self.assertEqual(len(result.file_root.children), 1)
        self.assertEqual(result.file_root.children[0].lines, ['abc'])
        self.assertEqual(result.file_root.children[0].get_id(), 'A')
        self.assertEqual(len(result.file_root.children[0].children), 0)
        self.assertEqual(len(result.parsing_errors), 0)
        
        
class Test_FileRoot(unittest.TestCase):
    def test_convert_index_to_id(self):
        self.assertEqual(FileRoot.convert_index_to_id(0), 'A')
        self.assertEqual(FileRoot.convert_index_to_id(1), 'B')
        self.assertEqual(FileRoot.convert_index_to_id(24), 'Z')
        self.assertEqual(FileRoot.convert_index_to_id(25), 'BA')
        self.assertEqual(FileRoot.convert_index_to_id(26), 'BB')
        self.assertEqual(FileRoot.convert_index_to_id(49), 'BZ')
        self.assertEqual(FileRoot.convert_index_to_id(50), 'CA')
        self.assertEqual(FileRoot.convert_index_to_id(625), 'BAA')
        
    def test_add_sibling_after(self):
        # after first top section - its also the last one
        data = FileFormat("# A\nabc")
        result = data.file_root.add_sibling_after('A')
        self.assertEqual(result, 'B')
        self.assertEqual(len(data.file_root.children), 2)
        self.assertEqual(data.file_root.children[0].lines, ['abc'])
        self.assertEqual(data.file_root.children[0].get_id(), 'A')
        self.assertEqual(data.file_root.children[1].lines, [])
        self.assertEqual(data.file_root.children[1].get_id(), 'B')
        # after first top section - there are others
        data = FileFormat("# A\nabc\n# B\ndef")
        result = data.file_root.add_sibling_after('A')
        self.assertEqual(result, 'B')
        self.assertEqual(len(data.file_root.children), 3)
        self.assertEqual(data.file_root.children[0].lines, ['abc'])
        self.assertEqual(data.file_root.children[0].get_id(), 'A')
        self.assertEqual(data.file_root.children[1].lines, [])
        self.assertEqual(data.file_root.children[1].get_id(), 'B')
        self.assertEqual(data.file_root.children[2].lines, ['def'])
        self.assertEqual(data.file_root.children[2].get_id(), 'C')
        # after last top section
        data = FileFormat("# A\nabc\n# B\ndef")
        result = data.file_root.add_sibling_after('B')
        self.assertEqual(result, 'C')
        self.assertEqual(len(data.file_root.children), 3)
        self.assertEqual(data.file_root.children[0].lines, ['abc'])
        self.assertEqual(data.file_root.children[0].get_id(), 'A')
        self.assertEqual(data.file_root.children[1].lines, ['def'])
        self.assertEqual(data.file_root.children[1].get_id(), 'B')
        self.assertEqual(data.file_root.children[2].lines, [])
        self.assertEqual(data.file_root.children[2].get_id(), 'C')
        # after lower section
        data = FileFormat("# A\nabc\n## A.A\ndef")
        result = data.file_root.add_sibling_after('A.A')
        self.assertEqual(result, 'A.B')
        self.assertEqual(len(data.file_root.children), 1)
        self.assertEqual(data.file_root.children[0].lines, ['abc'])
        self.assertEqual(data.file_root.children[0].get_id(), 'A')
        self.assertEqual(len(data.file_root.children[0].children), 2)
        self.assertEqual(data.file_root.children[0].children[0].lines, ['def'])
        self.assertEqual(data.file_root.children[0].children[0].get_id(), 'A.A')
        self.assertEqual(data.file_root.children[0].children[1].lines, [])
        self.assertEqual(data.file_root.children[0].children[1].get_id(), 'A.B')
        # id not found
        data = FileFormat("# A\nabc")
        result = data.file_root.add_sibling_after('A.A')
        self.assertEqual(result, None)
        self.assertEqual(len(data.file_root.children), 1)
        self.assertEqual(data.file_root.children[0].lines, ['abc'])
        self.assertEqual(data.file_root.children[0].get_id(), 'A')
        
    def test_add_first_child(self):
        # to empty root - no change b/c root has no id
        data = FileFormat("")
        result = data.file_root.add_first_child('A')
        self.assertEqual(result, None)
        self.assertEqual(len(data.file_root.children), 0)
        # to node with no children - adds child
        data = FileFormat("# A\nabc\n## A.A\ndef")
        result = data.file_root.add_first_child('A.A')
        self.assertEqual(result, "A.A.A")
        self.assertEqual(len(data.file_root.children), 1)
        self.assertEqual(data.file_root.children[0].lines, ['abc'])
        self.assertEqual(data.file_root.children[0].get_id(), 'A')
        self.assertEqual(len(data.file_root.children[0].children), 1)
        self.assertEqual(data.file_root.children[0].children[0].lines, ['def'])
        self.assertEqual(data.file_root.children[0].children[0].get_id(), 'A.A')
        self.assertEqual(len(data.file_root.children[0].children[0].children), 1)
        self.assertEqual(data.file_root.children[0].children[0].children[0].lines, [])
        self.assertEqual(data.file_root.children[0].children[0].children[0].get_id(), 'A.A.A')
        self.assertEqual(len(data.file_root.children[0].children[0].children[0].children), 0)
        # to node with children - no changes
        data = FileFormat("# A\nabc\n## A.A\ndef")
        result = data.file_root.add_first_child('A')
        self.assertEqual(result, None)
        self.assertEqual(len(data.file_root.children), 1)
        self.assertEqual(data.file_root.children[0].lines, ['abc'])
        self.assertEqual(data.file_root.children[0].get_id(), 'A')
        self.assertEqual(len(data.file_root.children[0].children), 1)
        self.assertEqual(data.file_root.children[0].children[0].lines, ['def'])
        self.assertEqual(data.file_root.children[0].children[0].get_id(), 'A.A')
        self.assertEqual(len(data.file_root.children[0].children[0].children), 0)
        
    def test_to_save_format(self):
        # empty root
        data = FileFormat("")
        result = data.file_root.to_save_format()
        self.assertEqual(result, "")
        # one child
        data = FileFormat("# A\nabc")
        result = data.file_root.to_save_format()
        self.assertEqual(result, "# A\n\nabc")
        # nested children
        data = FileFormat("# A\nabc\n## A.A\ndef\nghi\n# B\njkl")
        result = data.file_root.to_save_format()
        self.assertEqual(result, "# A\n\nabc\n\n## A.A\n\ndef\nghi\n\n# B\n\njkl")
        

class Test_FileSection(unittest.TestCase):
    def test_get_level(self):
        self.assertEqual(FileSection.get_level("abcdefg"), 0)
        self.assertEqual(FileSection.get_level(" # abc"), 0)
        self.assertEqual(FileSection.get_level("# abc"), 1)
        self.assertEqual(FileSection.get_level("#abc"), 1)
        self.assertEqual(FileSection.get_level("## abc"), 2)
        self.assertEqual(FileSection.get_level("##abc"), 2)
        self.assertEqual(FileSection.get_level("### abc"), 3)
        self.assertEqual(FileSection.get_level("###abc"), 3)
        self.assertEqual(FileSection.get_level("#### abc #"), 4)
        self.assertEqual(FileSection.get_level("####abc##"), 4)

if __name__ == "__main__":
    unittest.main()